<?php

Class FileStructure
{
    private $Build;
    private $FileName;

    public $Fields;
    public $Format;
    public $Localized;

    public function __construct($FileName, $Build){
        $this->FileName = $FileName;
        $this->Build = $Build;

        $File = strtok(strtolower($this->FileName), '.');
//        if(!array_key_exists($File, $this->FileStructure[$this->Build]))
//            return false;

        $this->Fields = array_map('trim', explode(',', $this->FileFields[$this->Build][$File]));
        $this->Format = $this->FileStructure[$this->Build][$File];
        if(strstr($this->Format, 'sxssxxsxsxxxxxxxx')) $this->Localized = 1; else $this->Localized = 0;
//        if (count($this->Fields) != strlen(str_ireplace('x', '', $this->Format)))
//        {
//            die("<strong>Critical Error:</strong> $FileName<br />Fields Count does not match File Format.<br /><i><strong>Wrong Patch Number Used?</strong></i><br /><strong>Expected: </strong>".count($this->Fields)."<br /><strong>Got: </strong>".strlen(str_ireplace('x', '', $this->Format)));
//            return;
//        }
    }


    public function getFileFormatString($FileExtension){
        $Formats = [
            'ADB'   =>  ['hex' => '0x32484357', 'dec' => '843596631', 'magic' => 'WCH2', 'headerSize' => '48'],
            'DB2'   =>  ['hex' => '0x32424457', 'dec' => '843203671', 'magic' => 'WDB2', 'headerSize' => '48'],
            'DB3'   =>  ['hex' => '0x33424457', 'dec' => '859980887', 'magic' => 'WDB3', 'headerSize' => '48'],
            'DBC'   =>  ['hex' => '0x43424457', 'dec' => '1128416343', 'magic' => 'WDBC', 'headerSize' => '20']
        ];
        $FormatString = $Formats[strtoupper($FileExtension)];
        $FormatString['formatString'] = $this->Format;
        return $FormatString;
    }

    private $FileStructure = [
        20726   =>  [
            'achievement'                   =>  'niiissiiiiisiii',
            'achievement_category'          =>  'nisi',
            'areagroup'                     =>  'n',
            'areagroupmember'               =>  'nii',
            'areatable'                     =>  'niiiiixxiisxisixxxxxixxxiiiix',
            'battlepetability'              =>  'nxxxxxss',
            'chartitles'                    =>  'nisxix',
            'chrclasses'                    =>  'nixsxxsxxxxxxxxxxxx',
            'chrraces'                      =>  'niixiixixxxsxxsxxxxxxxxxxxxxxxxxxxxxxxxx',
            'chrspecialization'             =>  'nsiixiiiixxsxxxx',
            //'creaturedisplayinfo'           =>  'niiiffissssiiiiiiiiiii',
            //'creaturedisplayinfoextra'      =>  'niiixxxxxxxxxxxxxxxxxx',
            //'creaturefamily'                =>  'nfifiiiiiiss',
            'currencycategory'              =>  'nisx',
            'currencytypes'                 =>  'nissxxxiiiis',
            'dungeonencounter'              =>  'niiiisiii',
            'dungeonmap'                    =>  'niiffffii',
            'durabilitycosts'               =>  'niiiiiiiiiiiiiiiiiiiiiiiiiiiii',
            'durabilityquality'             =>  'nf',
            'emotes'                        =>  'nsiiiiii',
            'emotestext'                    =>  'nsiiiixixixiixxixxx',
            'emotestextdata'                =>  'ns',
            'faction'                       =>  'nixxxxxxxxxxxxxxxxixxxxssxxx',
            'factiongroup'                  =>  'nixs',
            'factiontemplate'               =>  'niiiiiiiiiiiii',
            'garrability'                   =>  'nissiiii',
            'garrabilitycategory'           =>  'ns',
            //'garrabilityeffect'             =>  'niiiiiiiiiii',
            'garrbuilding'                  =>  'niiiiissssiiiiiiiiiiiiii',
            'garrbuildingplotinst'          =>  'niiiff',
            'garrclassspec'                 =>  'nsxxii',
            //'garrencounter'                 =>  'nisffii',
            //'garrencounterxmechanic'        =>  'nii',
            //'garrfollitemset'               =>  'n',
            //'garrfollitemsetmember'         =>  'niiii',
            'garrfollower'                  =>  'niiiiiiiiiiiiiiissiiiiii',
            'garrfollowerlevelxp'           =>  'niixx',
            'garrfollowerquality'           =>  'niixx',
            //'garrfollowertype'              =>  'niiii',
            'garrfollowerxability'          =>  'niii',
            'garrmechanic'                  =>  'nif',
            'garrmechanictype'              =>  'nissi',
            'garrmission'                   =>  'niiiixiiiiiisssiiiiiiiiff',
            'garrmissionreward'             =>  'niiiiiiixxi',
            //'garrmissiontype'               =>  'niii',
            'garrmissionxencounter'         =>  'nii',
            'garrmssnbonusability'          =>  'nxiifi',
            'gemproperties'                 =>  'niiiii',
            'glyphexclusivecategory'        =>  'ns',
            'glyphproperties'               =>  'niiii',
            'glyphrequiredspec'             =>  'nii',
            'glyphslot'                     =>  'nii',
            'gtarmormitigationbylvl'        =>  'nf',
            'gtbattlepettypedamagemod'      =>  'nf',
            'gtbattlepetxp'                 =>  'nf',
            'gtchancetomeleecrit'           =>  'nf',
            'gtchancetomeleecritbase'       =>  'nf',
            'gtchancetospellcrit'           =>  'nf',
            'gtchancetospellcritbase'       =>  'nf',
            'gtcombatratings'               =>  'nf',
            'gtitemsocketcostperlevel'      =>  'nf',
            'gtnpcmanacostscaler'           =>  'nf',
            'gtnpctotalhp'                  =>  'nf',
            'gtregenmpperspt'               =>  'nf',
            'gtspellscaling'                =>  'nf',
            'holidaydescriptions'           =>  'ns',
            'holidaynames'                  =>  'ns',
            'holidays'                      =>  'nxxxxxxxxxxxxxxxxxxxxxxxxxxxxixxxxxxxxxiisxix',
            'item'                          =>  'niiiiiiii',
            'itemappearance'                =>  'nii',
            'itemarmorquality'              =>  'nfffffffi',
            'itemarmorshield'               =>  'nifffffff',
            'itemarmortotal'                =>  'niffff',
            'itembagfamily'                 =>  'ns',
            'itembonus'                     =>  'niiiii',
            'itembonustreenode'             =>  'niiii',
            'itemclass'                     =>  'nifs',
            'itemcurrencycost'              =>  'ni',
            'itemdamageammo'                =>  'nfffffffi',
            'itemdamageonehand'             =>  'nfffffffi',
            'itemdamageonehandcaster'       =>  'nfffffffi',
            'itemdamageranged'              =>  'nfffffffi',
            'itemdamagethrown'              =>  'nfffffffi',
            'itemdamagetwohand'             =>  'nfffffffi',
            'itemdamagetwohandcaster'       =>  'nfffffffi',
            'itemdamagewand'                =>  'nfffffffi',
            'itemdisenchantloot'            =>  'niiiiii',
            'itemdisplayinfo'               =>  'nssxxsxxxxxxxxxxxxxxxxx',
            'itemeffect'                    =>  'niiiiiiiii',
            'itemextendedcost'              =>  'niiiiiiiiiiiiiiiiiiiiiiiiiiii',
            'itemgroupsounds'               =>  'niiii',
            'itemlimitcategory'             =>  'nsii',
            'itemnamedescription'           =>  'nsi',
            'itempetfood'                   =>  'ns',
            'itempricebase'                 =>  'niff',
            'itempurchasegroup'             =>  'niiiiiiiis',
            'itemrandomproperties'          =>  'nsiiiiis',
            'itemrandomsuffix'              =>  'nssiiiiiiiiii',
            'itemset'                       =>  'nsiiiiiiiiiixxxxxxxii',
            'itemsetspell'                  =>  'niiix',
            ''=>  '',
        ],
    ];

    private $FileFields = [
        20726   =>  [
            'achievement'                   =>  "id, faction, map, parent, name, description, category, points, ui_order, flags, icon, reward, minimum_criteria, shares_criteria, criteria_tree",
            'achievement_category'          =>  "id, parent, name, ui_order",
            'areagroup'                     =>  "id",
            'areagroupmember'               =>  "id, area_group_id, area_id",
            'areatable'                     =>  "id, continent_id, parent_area_id, area_bit, flags_first, flags_second, ambience_id, zone_music_id, name, exploration_level, area_name, faction_group_mask, mount_flags, world_pvp_id, pvp_combat_world_state_id, battle_pet_min_level, battle_pet_max_level",
            'battlepetability'              =>  "id, name, description",
            'chartitles'                    =>  "id, condition_id, name, mask_id",
            'chrclasses'                    =>  "id, power, name, name_upper",
            'chrraces'                      =>  "id, flags, faction_id, male_display, female_display, side, site_name, name",
            'chrspecialization'             =>  "id, background, class_id, mastery_bonus, list_order, pet_talent_type, char_role, icon, name",
            //'creaturedisplayinfo'           =>  "id, model_id, sound_id, display_id, model_scale, unk620, model_alpha, texture_variation_1, texture_variation_2, texture_variation_3, texture_name, portrait_display_id, size_class, blood_id, npc_sound_id, particle_color_id, geoset_data, effect_package_id, anim_replacement_set_id, flags, gender, spell_visual_kit",
            //'creaturedisplayinfoextra'      =>  "id, race, creature_type, gender",
            //'creaturefamily'                =>  "id, min_scale, min_scale_level, max_scale, max_scale_level, skill_line_1, skill_line_2, pet_food_mask, pet_talent_type, category_id, name, icon",
            'currencycategory'              =>  "id, flags, name",
            'currencytypes'                 =>  "id, category_id, name, icon, max_quantity, max_per_week, flags, quality, description",
            'dungeonencounter'              =>  "id, map_id, difficulty_id, list_order, bit, name, creature_display_id, spell_icon_id, flags",
            'dungeonmap'                    =>  "id, map_id, floor, min_y, max_y, min_x, max_x, area_id, flags",
            'durabilitycosts'               =>  "id, weapon_class_cost_1, weapon_class_cost_2, weapon_class_cost_3, weapon_class_cost_4, weapon_class_cost_5, weapon_class_cost_6, weapon_class_cost_7, weapon_class_cost_8, weapon_class_cost_9, weapon_class_cost_10, weapon_class_cost_11, weapon_class_cost_12, weapon_class_cost_13, weapon_class_cost_14, weapon_class_cost_15, weapon_class_cost_16, weapon_class_cost_17, weapon_class_cost_18, weapon_class_cost_19, weapon_class_cost_20, weapon_class_cost_21, armor_class_cost_1, armor_class_cost_2, armor_class_cost_3, armor_class_cost_4, armor_class_cost_5, armor_class_cost_6, armor_class_cost_7, armor_class_cost_8",
            'durabilityquality'             =>  "id, modifier",
            'emotes'                        =>  "id, command, animation_id, flags, spec_proc, spec_proc_param, sound_id, visual_kit_id",
            'emotestext'                    =>  "id, command, animation_id, third_person, second_person, first_person, second_no_target, first_no_target, third_person_female, second_person_female, second_no_target_female",
            'emotestextdata'                =>  "id, text",
            'faction'                       =>  "id, reputation_id, team, name, description",
            'factiongroup'                  =>  "id, mask_id, name",
            'factiontemplate'               =>  "id, faction_id, flags, faction_mask, friendly_mask, hostile_mask, enemy_faction_id_1, enemy_faction_id_2, enemy_faction_id_3, enemy_faction_id_4, friend_faction_id_1, friend_faction_id_2, friend_faction_id_3, friend_faction_id_4",
            'garrability'                   =>  "id, flags, name, description, icon, other_faction_ability, category_id, follower_type",
            'garrabilitycategory'           =>  "id, name",
            //'garrabilityeffect'             =>  "",
            'garrbuilding'                  =>  "id, horde_game_object, alliance_game_object, unknown, type, level, name_alliance, name_horde, description, tooltip, build_duration, currency_id, currency_amount, horde_prefix, alliance_prefix, icon, bonus_amount, flags, alliance_activation_scene_id, horde_activation_scene_id, max_shipments, follower_ability_id, follower_effect_id, cost_money",
            'garrbuildingplotinst'          =>  "id, building_id, texture_id, level_id, offset_x, offset_y",
            'garrclassspec'                 =>  "id, name_male, class_id, item_set_id",
            //'garrencounter'                 =>  "id, creature_id, creature_name, ",
            //'garrencounterxmechanic'        =>  "id, unknown1, unknown2",
            //'garrfollitemset'               =>  "id",
            //'garrfollitemsetmember'         =>  "",
            'garrfollower'                  =>  "id, follower_type, horde_id, alliance_id, horde_animation_id, alliance_animation_id, quality, horde_class_id, alliance_class_id, horde_itemset_id, alliance_itemset_id, level, weapon_itemlevel, armor_itemlevel, unknown1, flags, horde_text, alliance_text, unknown2, unknown3, horde_portrait_id, alliance_portrait_id, horde_list_id, alliance_list_id",
            'garrfollowerlevelxp'           =>  "id, level, exp_needed",
            'garrfollowerquality'           =>  "id, quality, exp_needed",
            //'garrfollowertype'              =>  "",
            'garrfollowerxability'          =>  "id, follower_id, ability_id, faction",
            'garrmechanic'                  =>  "id, mechanics_type, unknown",
            'garrmechanictype'              =>  "id, type, name, description, icon",
            'garrmission'                   =>  "id, level, required_itemlevel, threat_type, followers_required, duration, cooldown, unknown8, unknown9, category_id, missions_type, name, description, location, unknown14, unknown15, currency_cost_count, currency_cost_id, is_rare, experience, base_chance, unknown21, position_x, position_y",
            'garrmissionreward'             =>  "id, mission_id, reward_experience, item_reward_id, reward_count, reward_currency_id, reward_currency_count, gains_experience, reward_ability_id",
            //'garrmissiontype'               =>  "id, unknown2, unknown3, unknown4",
            'garrmissionxencounter'         =>  "id, mission_id, encounter_id",
            'garrmssnbonusability'          =>  "id, unknown2, ability_id, unknown4, duration",
            'gemproperties'                 =>  "id, enchant_id, max_inventory, max_total, type, min_item_level",
            'glyphexclusivecategory'        =>  "id, name",
            'glyphproperties'               =>  "id, spell_id, type, icon, exclusive_category_id",
            'glyphrequiredspec'             =>  "id, property_id, spec_id",
            'glyphslot'                     =>  "id, type, tooltip",
            'gtarmormitigationbylvl'        =>  "id, mitigation",
            'gtbattlepettypedamagemod'      =>  "id, multiplier",
            'gtbattlepetxp'                 =>  "id, experience",
            'gtchancetomeleecrit'           =>  "id, chance",
            'gtchancetomeleecritbase'       =>  "id, chance",
            'gtchancetospellcrit'           =>  "id, chance",
            'gtchancetospellcritbase'       =>  "id, chance",
            'gtcombatratings'               =>  "id, rating",
            'gtitemsocketcostperlevel'      =>  "id, cost",
            'gtnpcmanacostscaler'           =>  "id, cost",
            'gtnpctotalhp'                  =>  "id, modifier",
            'gtregenmpperspt'               =>  "id, modifier",
            'gtspellscaling'                =>  "id, modifier",
            'holidaydescriptions'           =>  "id, description",
            'holidaynames'                  =>  "id, name",
            'holidays'                      =>  "id, looping, name_id, description_id, texture_name, schedule_type",
            'item'                          =>  "id, class, subclass, sound_override_subclass, material, inventory_type, sheath, file_data_id, group_sounds_id",
            'itemappearance'                =>  "id, display_id, icon",
            'itemarmorquality'              =>  "id, quality_mod_1, quality_mod_2, quality_mod_3, quality_mod_4, quality_mod_5, quality_mod_6, quality_mod_7, item_level",
            'itemarmorshield'               =>  "id, item_level, quality_mod_1, quality_mod_2, quality_mod_3, quality_mod_4, quality_mod_5, quality_mod_6, quality_mod_7",
            'itemarmortotal'                =>  "id, item_level, cloth, leather, mail, plate",
            'itembagfamily'                 =>  "id, name",
            'itembonus'                     =>  "id, list_id, type, value_1, value_2, index",
            'itembonustreenode'             =>  "id, tree_id, tree_mod_id, sub_tree_id, list_id",
            'itemclass'                     =>  "id, flags, price_modifier, name",
            'itemcurrencycost'              =>  "id, item_id",
            'itemdamageammo'                =>  "id, quality_mod_1, quality_mod_2, quality_mod_3, quality_mod_4, quality_mod_5, quality_mod_6, quality_mod_7, item_level",
            'itemdamageonehand'             =>  "id, quality_mod_1, quality_mod_2, quality_mod_3, quality_mod_4, quality_mod_5, quality_mod_6, quality_mod_7, item_level",
            'itemdamageonehandcaster'       =>  "id, quality_mod_1, quality_mod_2, quality_mod_3, quality_mod_4, quality_mod_5, quality_mod_6, quality_mod_7, item_level",
            'itemdamageranged'              =>  "id, quality_mod_1, quality_mod_2, quality_mod_3, quality_mod_4, quality_mod_5, quality_mod_6, quality_mod_7, item_level",
            'itemdamagethrown'              =>  "id, quality_mod_1, quality_mod_2, quality_mod_3, quality_mod_4, quality_mod_5, quality_mod_6, quality_mod_7, item_level",
            'itemdamagetwohand'             =>  "id, quality_mod_1, quality_mod_2, quality_mod_3, quality_mod_4, quality_mod_5, quality_mod_6, quality_mod_7, item_level",
            'itemdamagetwohandcaster'       =>  "id, quality_mod_1, quality_mod_2, quality_mod_3, quality_mod_4, quality_mod_5, quality_mod_6, quality_mod_7, item_level",
            'itemdamagewand'                =>  "id, quality_mod_1, quality_mod_2, quality_mod_3, quality_mod_4, quality_mod_5, quality_mod_6, quality_mod_7, item_level",
            'itemdisenchantloot'            =>  "id, class, subclass, quality, min_item_level, max_item_level, required_skill",
            'itemdisplayinfo'               =>  "id, left_name, right_name, inventory_icon",
            'itemeffect'                    =>  "id, item_id, order_index, spell_id, trigger, charges, cooldown, category, category_cooldown, char_spec_id",
            'itemextendedcost'              =>  "id, required_arena_slot, required_item_1, required_item_2, required_item_3, required_item_4, required_item_5, required_item_count_1, required_item_count_2, required_item_count_3, required_item_count_4, required_item_count_5, required_personal_rating, item_purchase_group, required_currency_1, required_currency_2, required_currency_3, required_currency_4, required_currency_5, required_currency_count_1, required_currency_count_2, required_currency_count_3, required_currency_count_4, required_currency_count_5, required_faction_id, required_faction_standing, requirement_flags, required_achievement, required_money",
            'itemgroupsounds'               =>  "id, sound_1, sound_2, sound_3, sound_4",
            'itemlimitcategory'             =>  "id, name, quantity, flags",
            'itemnamedescription'           =>  "id, description, color",
            'itempetfood'                   =>  "id, name",
            'itempricebase'                 =>  "id, item_level, armor_factor, weapon_factor",
            'itempurchasegroup'             =>  "id, item1, item2, item3, item4, item5, item6, item7, item8, description",
            'itemrandomproperties'          =>  "id, internal_name, enchantment1, enchantment2, enchantment3, enchantment4, enchantment5, name",
            'itemrandomsuffix'              =>  "id, name, internal_name, enchantment1, enchantment2, enchantment3, enchantment4, enchantment5, allocationPct1, allocationPct2, allocationPct3, allocationPct4, allocationPct5",
            'itemset'                       =>  "id, name, item1, item2, item3, item4, item5, item6, item7, item8, item9, item10, skill_id, skill_rank",
            'itemsetspell'                  =>  "id, set_id, spell_id, threshold",
            ''=>  "",
        ],
    ];
}