<?php
require_once('Classes/DBC2Array.Class.php');
Class SQLGenerator
{
	private static $DBCDirectory;
	private static $Locale;

	public function __construct($DBCDir, $Loc)
	{
		SQLGenerator::$DBCDirectory = $DBCDir;
		SQLGenerator::$Locale = $Loc;
	}

    public static function DBCVersion($FileName, $Format)
    {
        $File = fopen(SQLGenerator::$DBCDirectory.$FileName, "rb") or die("Cannot open file " . $FileName . "\n");
        print_r(unpack("VrecordCount/VfieldCount/VrecordSize/VstringSize", fread($File, 16)));
    }

	public static function Unpack($Filename, $Format, $MapGenerator = false)
	{
		if (@stat(SQLGenerator::$DBCDirectory . $Filename) == NULL) 
			$Filename = strtolower($Filename);
		if(!$MapGenerator)
			echo base64_decode(SQLGenerator::GetHeader($Filename));
    	return DBC2Array::Convert(SQLGenerator::$DBCDirectory . $Filename, $Format);
	}

	public static function PrintSQL($Header, $Data)
	{
		$Size = 0;
		echo "$Header\n";
		foreach($Data as $Row)
		{
			if ($Size)
			{
				if ($Size > 937420)
				{
					echo ";\n\n\n$Header\n";
					$Size = 0;
				}
				else
					echo ",\n";
			}

			foreach($Row as $i => $Value)
				if (!is_int($Value) && !is_float($Value)) $Row[$i] = "'" . str_replace("\r\n", "\\n", addslashes($Value)) . "'";
			
			$Output = "(".implode(", ", $Row).")";
			$Size += strlen($Output);
			echo $Output;
		}
		echo ";\n\n";
	}

	public static function PrintUpdate($Table, $Data, $Keys, $Values)
	{
		echo "\n";
		foreach ($Data as $Row)
		{
			$Where = array();
			foreach ($Keys as $i => $name)
				$Where[] = "`$name` = " . "'" . str_replace("\r\n", "\\n", addslashes($Row[$i])) . "'";

			$Set = array();
			foreach ($Values as $i => $name)
				$Set[] = "`$name` = " . "'" . str_replace("\r\n", "\\n", addslashes($Row[$i])) . "'";

			echo "UPDATE $Table SET " , implode(", ", $Set) , " WHERE " , implode(" AND ", $Where), ";\n";
		}
	}

	public static function Localize($Format)
	{
		$Result = $Format;
		for ($i=0; $i<strlen($Format); $i++)
			if ($Format[$i] == 'S')
			{
				$Result[$i] = 'x';
				$Result[$i+SQLGenerator::$Locale] = 's';
			}
		return $Result;
	}

	public static function RemovePath($UnpackedDBC)
	{
		foreach ($UnpackedDBC as $i => $Row) 
			$UnpackedDBC[$i][1] = substr(strrchr($UnpackedDBC[$i][1],"\\"),1);
		return $UnpackedDBC;
	}

	public static function Factionize($UnpackedDBC)
	{
		$HordeID = 1801;
		$HordeRow = array();
		foreach ($UnpackedDBC as $Row) if ($Row[0] == $HordeID) $HordeRow = $Row;
		$AllianceID = 1802;
		$AllianceRow = array();
		foreach ($UnpackedDBC as $Row) if ($Row[0] == $AllianceID) $AllianceRow = $Row;
		$FactionAlliance = array();
		$FactionHorde = array();
		foreach ($UnpackedDBC as $i => $Row)
		{
			$Alliance = 0;
			if ($Row[5]==$AllianceID || $Row[6]==$AllianceID || $Row[7]==$AllianceID || $Row[7]==$AllianceID)
				$Alliance = -1;
			else if ($Row[9]==$AllianceID || $Row[10]==$AllianceID || $Row[11]==$AllianceID || $Row[12]==$AllianceID)
				$Alliance = 1;
			else if (($Row[3] & $AllianceRow[2]) != 0 || ($Row[2] & $AllianceRow[3]) != 0)
				$Alliance = 1;
			else if (($Row[4] & $AllianceRow[2]) != 0 || ($Row[2] & $AllianceRow[4]) != 0)
				$Alliance = -1;
			$FactionAlliance[$Row[1]] = $Alliance;

			$Horde = 0;
			if ($Row[5]==$HordeID || $Row[6]==$HordeID || $Row[7]==$HordeID || $Row[7]==$HordeID)
				$Horde = -1;
			else if ($Row[9]==$HordeID || $Row[10]==$HordeID || $Row[11]==$HordeID || $Row[12]==$HordeID)
				$Horde = 1;
			else if (($Row[3] & $HordeRow[2]) != 0 || ($Row[2] & $HordeRow[3]) != 0)
				$Horde = 1;
			else if (($Row[4] & $HordeRow[2]) != 0 || ($Row[2] & $HordeRow[4]) != 0)
				$Horde = -1;
			$FactionHorde[$Row[1]] = $Horde;

			$UnpackedDBC[$i][2] = $Alliance;
			$UnpackedDBC[$i][3] = $Horde;
			unset($UnpackedDBC[$i][4]);
			unset($UnpackedDBC[$i][5]);
			unset($UnpackedDBC[$i][6]);
			unset($UnpackedDBC[$i][7]);
			unset($UnpackedDBC[$i][8]);
			unset($UnpackedDBC[$i][9]);
			unset($UnpackedDBC[$i][10]);
			unset($UnpackedDBC[$i][11]);
			unset($UnpackedDBC[$i][12]);
		}
		return $UnpackedDBC;
	}

	public static function GetSide($UnpackedDBC)
	{
		foreach ($UnpackedDBC as $i => $Row)
		{
			$UnpackedDBC[$i][4] = $UnpackedDBC[$i][3];
			$UnpackedDBC[$i][3] = 0;
			if (isset($FactionAlliance[$Row[0]]) && isset($FactionHorde[$Row[0]]))
			{
				if ($FactionAlliance[$Row[0]] == 1 && $FactionHorde[$Row[0]] == -1)
					$UnpackedDBC[$i][3] = 1;
				if ($FactionAlliance[$Row[0]] == -1 && $FactionHorde[$Row[0]] == 1)
					$UnpackedDBC[$i][3] = 2;
			}
		}
	    return $UnpackedDBC;
	}

	public static function MapGenerator($DBCArray)
	{
		$FinalDBC		=	array();
		$MapDBC			=	$DBCArray[0][0];
		$MapFormat		=	$DBCArray[0][1];
		$AreaDBC		=	$DBCArray[1][0];
		$AreaFormat		=	$DBCArray[1][1];
		$WorldMapDBC	=	$DBCArray[2][0];
		$WorldMapFormat	=	$DBCArray[2][1];

		$MapType	=	array();
		$AreaType	=	array();

		$TempDBC = SQLGenerator::Unpack($MapDBC, $MapFormat, true);
		foreach ($TempDBC as $Row)
		{
			$MapType[$Row[0]] = $Row[1];
			if ($Row[3]) $AreaType[$Row[0] . "@" . $Row[3]] = $Row[1];
		}

		$TempDBC = SQLGenerator::Unpack($AreaDBC, $AreaFormat, true);
		foreach ($TempDBC as $Row)
		{
			$Type = 0;
			if (isset($maptype[$Row[1]]))
				$Type = $maptype[$Row[1]];
			if (isset($areatype[$Row[1]."@".$Row[0]]))
				$Type = $areatype[$Row[1]."@".$Row[0]];
			$FinalDBC[$Row[0]] = array($Row[1], $Row[0], $Row[2], 0, 0, 0, 0, $Type);
		}

		$TempDBC = SQLGenerator::Unpack($WorldMapDBC, $WorldMapFormat, true);
		foreach ($TempDBC as $Row)
		{
			if (isset($FinalDBC[$Row[1]]))
			{
				$FinalDBC[$Row[1]][3] = ($Row[5]<$Row[6]) ? $Row[5] : $Row[6];
				$FinalDBC[$Row[1]][4] = ($Row[3]<$Row[4]) ? $Row[3] : $Row[4];
				$FinalDBC[$Row[1]][5] = ($Row[5]<$Row[6]) ? $Row[6] : $Row[5];
				$FinalDBC[$Row[1]][6] = ($Row[3]<$Row[4]) ? $Row[4] : $Row[3];
			}
		}
		unset($TempDBC);
		echo base64_decode(SQLGenerator::GetHeader('Group.dbc'));
		return $FinalDBC;
	}

	public static function GetHeader($DBCName)
	{
		$Headers = array(
			"Achievement_Category.dbc" => "LS0gQWNoaWV2ZW1lbnRfQ2F0ZWdvcnkuZGJjDQpEUk9QIFRBQkxFIElGIEVYSVNUUyBgZnJlZWRvbWhlYWRfYWNoaWV2ZW1lbnRjYXRlZ29yeWA7DQpDUkVBVEUgVEFCTEUgYGZyZWVkb21oZWFkX2FjaGlldmVtZW50Y2F0ZWdvcnlgICgNCiAgYGlkYCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMLA0KICBgcGFyZW50QWNoaWV2ZW1lbnRgIG1lZGl1bWludCgxMSkgTk9UIE5VTEwsDQogIGBuYW1lX2xvYzBgIHZhcmNoYXIoMjU1KSBOT1QgTlVMTCwNCiAgUFJJTUFSWSBLRVkgKGBpZGApLA0KICBJTkRFWCBgaWR4X2FjaGlldmVtZW50YChgcGFyZW50QWNoaWV2ZW1lbnRgKQ0KKSBFTkdJTkU9TXlJU0FNIERFRkFVTFQgQ0hBUlNFVD11dGY4IFJPV19GT1JNQVQ9RklYRUQ7",
			"Achievement.dbc" => "PGJyIC8+PGJyIC8+LS0gQWNoaWV2ZW1lbnQuZGJjCkRST1AgVEFCTEUgSUYgRVhJU1RTIGBmcmVlZG9taGVhZF9hY2hpZXZlbWVudGA7CkNSRUFURSBUQUJMRSBgZnJlZWRvbWhlYWRfYWNoaWV2ZW1lbnRgICgKICBgaWRgIG1lZGl1bWludCgxMSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYGZhY3Rpb25gIHRpbnlpbnQoMSkgTk9UIE5VTEwsCiAgYG1hcGAgbWVkaXVtaW50KDExKSBOT1QgTlVMTCwKICBgcGFyZW50YCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGBuYW1lX2xvYzBgIHZhcmNoYXIoMjU1KSBOT1QgTlVMTCwKICBgZGVzY3JpcHRpb25fbG9jMGAgdmFyY2hhcigyNTUpIE5PVCBOVUxMLAogIGBjYXRlZ29yeWAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgcG9pbnRzYCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGBvcmRlcmAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgZmxhZ3NgIG1lZGl1bWludCgxMSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYGljb25gIG1lZGl1bWludCgxMSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYHJld2FyZF9sb2MwYCB2YXJjaGFyKDI1NSkgTk9UIE5VTEwsCiAgYGNvdW50YCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGByZWZBY2hpZXZlbWVudGAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBQUklNQVJZIEtFWSAoYGlkYCksCiAgSU5ERVggYGlkeF9jYXRlZ29yeWAoYGNhdGVnb3J5YCksCiAgSU5ERVggYGlkeF9wYXJlbnRgKGBwYXJlbnRgKQopIEVOR0lORT1NeUlTQU0gREVGQVVMVCBDSEFSU0VUPXV0ZjggUk9XX0ZPUk1BVD1GSVhFRDs=",
			"Achievement_Criteria.dbc" => "PGJyIC8+PGJyIC8+LS0gQWNoaWV2ZW1lbnRfQ3JpdGVyaWEuZGJjCkRST1AgVEFCTEUgSUYgRVhJU1RTIGBmcmVlZG9taGVhZF9hY2hpZXZlbWVudGNyaXRlcmlhYDsKQ1JFQVRFIFRBQkxFIGBmcmVlZG9taGVhZF9hY2hpZXZlbWVudGNyaXRlcmlhYCAoCiAgYGlkYCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGByZWZBY2hpZXZlbWVudGAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgdHlwZWAgbWVkaXVtaW50KDExKSBOT1QgTlVMTCwKICBgdmFsdWUxYCBpbnQoMTEpIE5PVCBOVUxMLAogIGB2YWx1ZTJgIGludCgxMSkgTk9UIE5VTEwsCiAgYHZhbHVlM2AgaW50KDExKSBOT1QgTlVMTCwKICBgdmFsdWU0YCBpbnQoMTEpIE5PVCBOVUxMLAogIGB2YWx1ZTVgIGludCgxMSkgTk9UIE5VTEwsCiAgYHZhbHVlNmAgaW50KDExKSBOT1QgTlVMTCwKICBgbmFtZV9sb2MwYCB2YXJjaGFyKDI1NSkgTk9UIE5VTEwsCiAgYGNvbXBsZXRlX2ZsYWdzYCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGBncm91cF9mbGFnc2AgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgdGltZWxpbWl0YCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGBvcmRlcmAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBQUklNQVJZIEtFWSAoYGlkYCksCiAgSU5ERVggYGlkeF9hY2hpZXZlbWVudGAoYHJlZkFjaGlldmVtZW50YCkKKSBFTkdJTkU9TXlJU0FNIERFRkFVTFQgQ0hBUlNFVD11dGY4IFJPV19GT1JNQVQ9RklYRUQ7",
			"GlyphProperties.dbc" => "PGJyIC8+PGJyIC8+LS0gR2x5cGhQcm9wZXJ0aWVzLmRiYwpEUk9QIFRBQkxFIElGIEVYSVNUUyBgZnJlZWRvbWhlYWRfZ2x5cGhwcm9wZXJ0aWVzYDsKQ1JFQVRFIFRBQkxFIGBmcmVlZG9taGVhZF9nbHlwaHByb3BlcnRpZXNgICgKICBgaWRgIG1lZGl1bWludCgxMSkgTk9UIE5VTEwsCiAgYHNwZWxsaWRgIG1lZGl1bWludCgxMSkgTk9UIE5VTEwsCiAgYHR5cGVmbGFnc2AgbWVkaXVtaW50KDExKSBOT1QgTlVMTCwKICBgaWNvbmlkYCBtZWRpdW1pbnQoMTEpIE5PVCBOVUxMCikgRU5HSU5FPU15SVNBTSBERUZBVUxUIENIQVJTRVQ9dXRmOCBST1dfRk9STUFUPUZJWEVEOw==",
			"Item.dbc" => "PGJyIC8+PGJyIC8+LS0gSXRlbS5kYmMKRFJPUCBUQUJMRSBJRiBFWElTVFMgYGZyZWVkb21oZWFkX2l0ZW1zYDsKQ1JFQVRFIFRBQkxFIGBmcmVlZG9taGVhZF9pdGVtc2AgKAogIGBlbnRyeWAgbWVkaXVtaW50KDgpIHVuc2lnbmVkIE5PVCBOVUxMIGRlZmF1bHQgJzAnLAogIGBjbGFzc2AgdGlueWludCgzKSB1bnNpZ25lZCBOT1QgTlVMTCBkZWZhdWx0ICcwJywKICBgc3ViY2xhc3NgIHRpbnlpbnQoMykgdW5zaWduZWQgTk9UIE5VTEwgZGVmYXVsdCAnMCcsCiAgYE1hdGVyaWFsYCB0aW55aW50KDQpIE5PVCBOVUxMIGRlZmF1bHQgJzAnLAogIGBkaXNwbGF5aWRgIG1lZGl1bWludCg4KSB1bnNpZ25lZCBOT1QgTlVMTCBkZWZhdWx0ICcwJywKICBgSW52ZW50b3J5VHlwZWAgdGlueWludCgzKSB1bnNpZ25lZCBOT1QgTlVMTCBkZWZhdWx0ICcwJywKICBgc2hlYXRoYCB0aW55aW50KDMpIHVuc2lnbmVkIE5PVCBOVUxMIGRlZmF1bHQgJzAnLAogIFBSSU1BUlkgS0VZICAoYGVudHJ5YCkKKSBFTkdJTkU9TXlJU0FNIERFRkFVTFQgQ0hBUlNFVD11dGY4IFJPV19GT1JNQVQ9RklYRUQ7",
			"CharTitles.dbc" => "PGJyIC8+PGJyIC8+LS0gQ2hhclRpdGxlcy5kYmMKRFJPUCBUQUJMRSBJRiBFWElTVFMgYGZyZWVkb21oZWFkX2NoYXJfdGl0bGVzYDsKQ1JFQVRFIFRBQkxFIGBmcmVlZG9taGVhZF9jaGFyX3RpdGxlc2AgKAogIGBpZGAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgbmFtZV9sb2MwYCB2YXJjaGFyKDI1NSkgTk9UIE5VTEwsCiAgUFJJTUFSWSBLRVkgIChgaWRgKQopIEVOR0lORT1NeUlTQU0gREVGQVVMVCBDSEFSU0VUPXV0ZjggUk9XX0ZPUk1BVD1GSVhFRDs=",
			"ItemExtendedCost.dbc" => "PGJyIC8+PGJyIC8+LS0gSXRlbUV4dGVuZGVkQ29zdC5kYmMKRFJPUCBUQUJMRSBJRiBFWElTVFMgYGZyZWVkb21oZWFkX2l0ZW1fZXh0ZW5kZWRfY29zdGA7CkNSRUFURSBUQUJMRSBgZnJlZWRvbWhlYWRfaXRlbV9leHRlbmRlZF9jb3N0YCAoCiAgYGV4dGVuZGVkY29zdElEYCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGByZXFob25vcnBvaW50c2AgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgcmVxYXJlbmFwb2ludHNgIG1lZGl1bWludCgxMSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYHJlcWl0ZW0xYCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGByZXFpdGVtMmAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgcmVxaXRlbTNgIG1lZGl1bWludCgxMSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYHJlcWl0ZW00YCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGByZXFpdGVtNWAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgcmVxaXRlbWNvdW50MWAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgcmVxaXRlbWNvdW50MmAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgcmVxaXRlbWNvdW50M2AgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgcmVxaXRlbWNvdW50NGAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgcmVxaXRlbWNvdW50NWAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgcmVxcGVyc29uYWxhcmVuYXJhdGluZ2AgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBQUklNQVJZIEtFWSAgKGBleHRlbmRlZGNvc3RJRGApCikgRU5HSU5FPU15SVNBTSBERUZBVUxUIENIQVJTRVQ9dXRmOCBST1dfRk9STUFUPUZJWEVEOw==",
			"SkillLineAbility.dbc" => "PGJyIC8+PGJyIC8+LS0gU2tpbGxMaW5lQWJpbGl0eS5kYmMKRFJPUCBUQUJMRSBJRiBFWElTVFMgYGZyZWVkb21oZWFkX3NraWxsX2xpbmVfYWJpbGl0eWA7CkNSRUFURSBUQUJMRSBgZnJlZWRvbWhlYWRfc2tpbGxfbGluZV9hYmlsaXR5YCAoCiAgYHNraWxsSURgIG1lZGl1bWludCgxMSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYHNwZWxsSURgIG1lZGl1bWludCgxMSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYHJhY2VtYXNrYCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGBjbGFzc21hc2tgIG1lZGl1bWludCgxMSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYHJlcV9za2lsbF92YWx1ZWAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgbWF4X3ZhbHVlYCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGBtaW5fdmFsdWVgIG1lZGl1bWludCgxMSkgdW5zaWduZWQgTk9UIE5VTEwKKSBFTkdJTkU9TXlJU0FNIERFRkFVTFQgQ0hBUlNFVD11dGY4IFJPV19GT1JNQVQ9RklYRUQ7CkFMVEVSIFRBQkxFIGBmcmVlZG9taGVhZF9za2lsbF9saW5lX2FiaWxpdHlgIEFERCBJTkRFWCBgc3BlbGxJRGAoYHNwZWxsSURgKTs=",
			"SkillLine.dbc" => "PGJyIC8+PGJyIC8+LS0gU2tpbGxMaW5lLmRiYwpEUk9QIFRBQkxFIElGIEVYSVNUUyBgZnJlZWRvbWhlYWRfc2tpbGxgOwpDUkVBVEUgVEFCTEUgYGZyZWVkb21oZWFkX3NraWxsYCAoCiAgYHNraWxsSURgIG1lZGl1bWludCgxMSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYGNhdGVnb3J5SURgIG1lZGl1bWludCgxMSkgTk9UIE5VTEwsCiAgYG5hbWVfbG9jMGAgdmFyY2hhcigyNTUpIE5PVCBOVUxMLAogIFBSSU1BUlkgS0VZICAoYHNraWxsSURgKQopIEVOR0lORT1NeUlTQU0gREVGQVVMVCBDSEFSU0VUPXV0ZjggUk9XX0ZPUk1BVD1GSVhFRDs=",
			"SpellDispelType.dbc" => "PGJyIC8+PGJyIC8+LS0gU3BlbGxEaXNwZWxUeXBlLmRiYwpEUk9QIFRBQkxFIElGIEVYSVNUUyBgZnJlZWRvbWhlYWRfc3BlbGxkaXNwZWx0eXBlYDsKQ1JFQVRFIFRBQkxFIGBmcmVlZG9taGVhZF9zcGVsbGRpc3BlbHR5cGVgICgKICBgaWRgIG1lZGl1bWludCgxMSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYG5hbWVfbG9jMGAgdmFyY2hhcigyNTUpIE5PVCBOVUxMLAogIFBSSU1BUlkgS0VZICAoYGlkYCkKKSBFTkdJTkU9TXlJU0FNIERFRkFVTFQgQ0hBUlNFVD11dGY4IFJPV19GT1JNQVQ9RklYRUQ7",
			"SpellMechanic.dbc" => "PGJyIC8+PGJyIC8+LS0gU3BlbGxNZWNoYW5pYy5kYmMKRFJPUCBUQUJMRSBJRiBFWElTVFMgYGZyZWVkb21oZWFkX3NwZWxsbWVjaGFuaWNgOwpDUkVBVEUgVEFCTEUgYGZyZWVkb21oZWFkX3NwZWxsbWVjaGFuaWNgICgKICBgaWRgIG1lZGl1bWludCgxMSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYG5hbWVfbG9jMGAgdmFyY2hhcigyNTUpIE5PVCBOVUxMLAogIFBSSU1BUlkgS0VZICAoYGlkYCkKKSBFTkdJTkU9TXlJU0FNIERFRkFVTFQgQ0hBUlNFVD11dGY4IFJPV19GT1JNQVQ9RklYRUQ7",
			"Resistances.dbc" => "PGJyIC8+PGJyIC8+LS0gUmVzaXN0YW5jZXMuZGJjCkRST1AgVEFCTEUgSUYgRVhJU1RTIGBmcmVlZG9taGVhZF9yZXNpc3RhbmNlc2A7CkNSRUFURSBUQUJMRSBgZnJlZWRvbWhlYWRfcmVzaXN0YW5jZXNgICgKICBgaWRgIG1lZGl1bWludCgxMSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYG5hbWVfbG9jMGAgdmFyY2hhcigyNTUpIE5PVCBOVUxMLAogIFBSSU1BUlkgS0VZICAoYGlkYCkKKSBFTkdJTkU9TXlJU0FNIERFRkFVTFQgQ0hBUlNFVD11dGY4IFJPV19GT1JNQVQ9RklYRUQ7",
			"SpellCastTimes.dbc" => "PGJyIC8+PGJyIC8+LS0gU3BlbGxDYXN0VGltZXMuZGJjCkRST1AgVEFCTEUgSUYgRVhJU1RTIGBmcmVlZG9taGVhZF9zcGVsbGNhc3R0aW1lc2A7CkNSRUFURSBUQUJMRSBgZnJlZWRvbWhlYWRfc3BlbGxjYXN0dGltZXNgICgKICBgaWRgIG1lZGl1bWludCgxMSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYGJhc2VgIG1lZGl1bWludCgxMSkgTk9UIE5VTEwsCiAgUFJJTUFSWSBLRVkgIChgaWRgKQopIEVOR0lORT1NeUlTQU0gREVGQVVMVCBDSEFSU0VUPXV0ZjggUk9XX0ZPUk1BVD1GSVhFRDs=",
			"SpellIcon.dbc" => "PGJyIC8+PGJyIC8+LS0gU3BlbGxJY29uLmRiYwpEUk9QIFRBQkxFIElGIEVYSVNUUyBgZnJlZWRvbWhlYWRfc3BlbGxpY29uc2A7CkNSRUFURSBUQUJMRSBgZnJlZWRvbWhlYWRfc3BlbGxpY29uc2AgKAogIGBpZGAgaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCBkZWZhdWx0ICcwJyBDT01NRU5UICdJY29uIElkZW50aWZpZXInLAogIGBpY29ubmFtZWAgdmFyY2hhcig1MCkgTk9UIE5VTEwgZGVmYXVsdCAnJyBDT01NRU5UICdJY29uIE5hbWUnLAogIFBSSU1BUlkgS0VZICAoYGlkYCkKKSBFTkdJTkU9TXlJU0FNIERFRkFVTFQgQ0hBUlNFVD11dGY4IFJPV19GT1JNQVQ9RklYRUQgQ09NTUVOVD0nSWNvbiBOYW1lcyc7",
			"Lock.dbc" => "PGJyIC8+PGJyIC8+LS0gTG9jay5kYmMKRFJPUCBUQUJMRSBJRiBFWElTVFMgYGZyZWVkb21oZWFkX2xvY2tgOwpDUkVBVEUgVEFCTEUgYGZyZWVkb21oZWFkX2xvY2tgICgKICBgbG9ja0lEYCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGB0eXBlMWAgdGlueWludCgxKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgdHlwZTJgIHRpbnlpbnQoMSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYHR5cGUzYCB0aW55aW50KDEpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGB0eXBlNGAgdGlueWludCgxKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgdHlwZTVgIHRpbnlpbnQoMSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYGxvY2twcm9wZXJ0aWVzMWAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgbG9ja3Byb3BlcnRpZXMyYCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGBsb2NrcHJvcGVydGllczNgIG1lZGl1bWludCgxMSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYGxvY2twcm9wZXJ0aWVzNGAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgbG9ja3Byb3BlcnRpZXM1YCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGByZXF1aXJlZHNraWxsMWAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgcmVxdWlyZWRza2lsbDJgIG1lZGl1bWludCgxMSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYHJlcXVpcmVkc2tpbGwzYCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGByZXF1aXJlZHNraWxsNGAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgcmVxdWlyZWRza2lsbDVgIG1lZGl1bWludCgxMSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgUFJJTUFSWSBLRVkgIChgbG9ja0lEYCkKKSBFTkdJTkU9TXlJU0FNIERFRkFVTFQgQ0hBUlNFVD11dGY4IFJPV19GT1JNQVQ9RklYRUQgQ09NTUVOVD0nTG9ja3MnOw==",
			"ItemDisplayInfo.dbc" => "PGJyIC8+PGJyIC8+LS0gSXRlbURpc3BsYXlJbmZvLmRiYwpEUk9QIFRBQkxFIElGIEVYSVNUUyBgZnJlZWRvbWhlYWRfaWNvbnNgOwpDUkVBVEUgVEFCTEUgYGZyZWVkb21oZWFkX2ljb25zYCAoCiAgYGlkYCBpbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMIGRlZmF1bHQgJzAnIENPTU1FTlQgJ0ljb24gSWRlbnRpZmllcicsCiAgYGljb25uYW1lYCB2YXJjaGFyKDI1NSkgTk9UIE5VTEwgZGVmYXVsdCAnJyBDT01NRU5UICdJY29uIE5hbWUnLAogIFBSSU1BUlkgS0VZICAoYGlkYCkKKSBFTkdJTkU9TXlJU0FNIERFRkFVTFQgQ0hBUlNFVD11dGY4IFJPV19GT1JNQVQ9RklYRUQgQ09NTUVOVD0nSWNvbiBOYW1lcyc7",
			"ItemSet.dbc" => "PGJyIC8+PGJyIC8+LS0gSXRlbVNldC5kYmMKRFJPUCBUQUJMRSBJRiBFWElTVFMgYGZyZWVkb21oZWFkX2l0ZW1zZXRgOwpDUkVBVEUgVEFCTEUgYGZyZWVkb21oZWFkX2l0ZW1zZXRgICgKICBgaXRlbXNldElEYCBzbWFsbGludCgzKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgbmFtZV9sb2MwYCB2YXJjaGFyKDI1NSkgTk9UIE5VTEwsCiAgYGl0ZW0xYCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGBpdGVtMmAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgaXRlbTNgIG1lZGl1bWludCgxMSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYGl0ZW00YCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGBpdGVtNWAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgaXRlbTZgIG1lZGl1bWludCgxMSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYGl0ZW03YCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGBpdGVtOGAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgaXRlbTlgIG1lZGl1bWludCgxMSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYGl0ZW0xMGAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgc3BlbGwxYCBtZWRpdW1pbnQoNSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYHNwZWxsMmAgbWVkaXVtaW50KDUpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGBzcGVsbDNgIG1lZGl1bWludCg1KSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgc3BlbGw0YCBtZWRpdW1pbnQoNSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYHNwZWxsNWAgbWVkaXVtaW50KDUpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGBzcGVsbDZgIG1lZGl1bWludCg1KSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgc3BlbGw3YCBtZWRpdW1pbnQoNSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYHNwZWxsOGAgbWVkaXVtaW50KDUpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGBib251czFgIHRpbnlpbnQoMSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYGJvbnVzMmAgdGlueWludCgxKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgYm9udXMzYCB0aW55aW50KDEpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGBib251czRgIHRpbnlpbnQoMSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYGJvbnVzNWAgdGlueWludCgxKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgYm9udXM2YCB0aW55aW50KDEpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGBib251czdgIHRpbnlpbnQoMSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYGJvbnVzOGAgdGlueWludCgxKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgc2tpbGxJRGAgc21hbGxpbnQoMykgdW5zaWduZWQgTk9UIE5VTEwsCiAgYHNraWxsbGV2ZWxgIHNtYWxsaW50KDMpIHVuc2lnbmVkIE5PVCBOVUxMLAogIFBSSU1BUlkgS0VZICAoYGl0ZW1zZXRJRGApCikgRU5HSU5FPU15SVNBTSBERUZBVUxUIENIQVJTRVQ9dXRmOCBST1dfRk9STUFUPUZJWEVEOw==",
			"Spell.dbc" => "PGJyIC8+PGJyIC8+LS0gU3BlbGwuZGJjCkRST1AgVEFCTEUgSUYgRVhJU1RTIGBmcmVlZG9taGVhZF9zcGVsbGA7CkNSRUFURSBUQUJMRSBgZnJlZWRvbWhlYWRfc3BlbGxgICgKICBgc3BlbGxJRGAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgcmVzaXN0YW5jZXNJRGAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgZGlzcGVsdHlwZUlEYCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGBtZWNoYW5pY0lEYCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGBzcGVsbGNhc3R0aW1lc0lEYCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGBjb29sZG93bmAgaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgQXVyYUludGVycnVwdEZsYWdzYCBpbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGBDaGFubmVsSW50ZXJydXB0RmxhZ3NgIGludCgxMSkgdW5zaWduZWQgTk9UIE5VTEwsIAogIGBwcm9jQ2hhbmNlYCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGBwcm9jQ2hhcmdlc2AgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgbGV2ZWxzcGVsbGAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwgCiAgYGR1cmF0aW9uSURgIHNtYWxsaW50KDMpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGBtYW5hY29zdGAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwgCiAgYHJhbmdlSURgIHRpbnlpbnQoMykgdW5zaWduZWQgTk9UIE5VTEwsCiAgYHN0YWNrYCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGB0b29sMWAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwgCiAgYHRvb2wyYCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMLCAKICBgcmVhZ2VudDFgIG1lZGl1bWludCgxMSkgTk9UIE5VTEwsIAogIGByZWFnZW50MmAgbWVkaXVtaW50KDExKSBOT1QgTlVMTCwgCiAgYHJlYWdlbnQzYCBtZWRpdW1pbnQoMTEpIE5PVCBOVUxMLCAKICBgcmVhZ2VudDRgIG1lZGl1bWludCgxMSkgTk9UIE5VTEwsIAogIGByZWFnZW50NWAgbWVkaXVtaW50KDExKSBOT1QgTlVMTCwgCiAgYHJlYWdlbnQ2YCBtZWRpdW1pbnQoMTEpIE5PVCBOVUxMLCAKICBgcmVhZ2VudDdgIG1lZGl1bWludCgxMSkgTk9UIE5VTEwsIAogIGByZWFnZW50OGAgbWVkaXVtaW50KDExKSBOT1QgTlVMTCwgCiAgYHJlYWdlbnRjb3VudDFgIG1lZGl1bWludCgxMSkgTk9UIE5VTEwsIAogIGByZWFnZW50Y291bnQyYCBtZWRpdW1pbnQoMTEpIE5PVCBOVUxMLCAKICBgcmVhZ2VudGNvdW50M2AgbWVkaXVtaW50KDExKSBOT1QgTlVMTCwgCiAgYHJlYWdlbnRjb3VudDRgIG1lZGl1bWludCgxMSkgTk9UIE5VTEwsIAogIGByZWFnZW50Y291bnQ1YCBtZWRpdW1pbnQoMTEpIE5PVCBOVUxMLCAKICBgcmVhZ2VudGNvdW50NmAgbWVkaXVtaW50KDExKSBOT1QgTlVMTCwgCiAgYHJlYWdlbnRjb3VudDdgIG1lZGl1bWludCgxMSkgTk9UIE5VTEwsIAogIGByZWFnZW50Y291bnQ4YCBtZWRpdW1pbnQoMTEpIE5PVCBOVUxMLCAKICBgZWZmZWN0MWlkYCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGBlZmZlY3QyaWRgIG1lZGl1bWludCgxMSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYGVmZmVjdDNpZGAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgZWZmZWN0MURpZVNpZGVzYCBpbnQoMTEpIHNpZ25lZCBOT1QgTlVMTCwKICBgZWZmZWN0MkRpZVNpZGVzYCBpbnQoMTEpIHNpZ25lZCBOT1QgTlVMTCwKICBgZWZmZWN0M0RpZVNpZGVzYCBpbnQoMTEpIHNpZ25lZCBOT1QgTlVMTCwKICBgZWZmZWN0MUJhc2VQb2ludHNgIGludCgxMSkgc2lnbmVkIE5PVCBOVUxMLAogIGBlZmZlY3QyQmFzZVBvaW50c2AgaW50KDExKSBzaWduZWQgTk9UIE5VTEwsCiAgYGVmZmVjdDNCYXNlUG9pbnRzYCBpbnQoMTEpIHNpZ25lZCBOT1QgTlVMTCwKICBgZWZmZWN0MXRhcmdldEFgIHNtYWxsaW50KDUpIHNpZ25lZCBOT1QgTlVMTCwKICBgZWZmZWN0MnRhcmdldEFgIHNtYWxsaW50KDUpIHNpZ25lZCBOT1QgTlVMTCwKICBgZWZmZWN0M3RhcmdldEFgIHNtYWxsaW50KDUpIHNpZ25lZCBOT1QgTlVMTCwKICBgZWZmZWN0MXRhcmdldEJgIHNtYWxsaW50KDUpIHNpZ25lZCBOT1QgTlVMTCwKICBgZWZmZWN0MnRhcmdldEJgIHNtYWxsaW50KDUpIHNpZ25lZCBOT1QgTlVMTCwKICBgZWZmZWN0M3RhcmdldEJgIHNtYWxsaW50KDUpIHNpZ25lZCBOT1QgTlVMTCwKICBgZWZmZWN0MXJhZGl1c2AgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgZWZmZWN0MnJhZGl1c2AgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgZWZmZWN0M3JhZGl1c2AgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgZWZmZWN0MUF1cmFgIHNtYWxsaW50KDUpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGBlZmZlY3QyQXVyYWAgc21hbGxpbnQoNSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYGVmZmVjdDNBdXJhYCBzbWFsbGludCg1KSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgZWZmZWN0MUFtcGxpdHVkZWAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgZWZmZWN0MkFtcGxpdHVkZWAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgZWZmZWN0M0FtcGxpdHVkZWAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgZWZmZWN0XzFfcHJvY192YWx1ZWAgZmxvYXQgTk9UIE5VTEwsCiAgYGVmZmVjdF8yX3Byb2NfdmFsdWVgIGZsb2F0IE5PVCBOVUxMLAogIGBlZmZlY3RfM19wcm9jX3ZhbHVlYCBmbG9hdCBOT1QgTlVMTCwKICBgZWZmZWN0MUNoYWluVGFyZ2V0YCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGBlZmZlY3QyQ2hhaW5UYXJnZXRgIG1lZGl1bWludCgxMSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYGVmZmVjdDNDaGFpblRhcmdldGAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgZWZmZWN0MWl0ZW10eXBlYCBpbnQoMTEpIE5PVCBOVUxMLCAKICBgZWZmZWN0Mml0ZW10eXBlYCBpbnQoMTEpIE5PVCBOVUxMLCAKICBgZWZmZWN0M2l0ZW10eXBlYCBpbnQoMTEpIE5PVCBOVUxMLCAKICBgZWZmZWN0MU1pc2NWYWx1ZWAgaW50KDExKSBOT1QgTlVMTCwKICBgZWZmZWN0Mk1pc2NWYWx1ZWAgaW50KDExKSBOT1QgTlVMTCwKICBgZWZmZWN0M01pc2NWYWx1ZWAgaW50KDExKSBOT1QgTlVMTCwKICBgZWZmZWN0MXRyaWdnZXJzcGVsbGAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgZWZmZWN0MnRyaWdnZXJzcGVsbGAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgZWZmZWN0M3RyaWdnZXJzcGVsbGAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgZWZmZWN0XzFfcHJvY19jaGFuY2VgIGZsb2F0IE5PVCBOVUxMLAogIGBlZmZlY3RfMl9wcm9jX2NoYW5jZWAgZmxvYXQgTk9UIE5VTEwsCiAgYGVmZmVjdF8zX3Byb2NfY2hhbmNlYCBmbG9hdCBOT1QgTlVMTCwKICBgc3BlbGxpY29uYCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMLCAKICBgc3BlbGxuYW1lX2xvYzBgIHZhcmNoYXIoMjU1KSBOT1QgTlVMTCwKICBgcmFua19sb2MwYCB0ZXh0IE5PVCBOVUxMLAogIGB0b29sdGlwX2xvYzBgIHRleHQgTk9UIE5VTEwsCiAgYGJ1ZmZfbG9jMGAgdGV4dCBOT1QgTlVMTCwKICBgbWFuYWNvc3RwZXJjZW50YCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGBhZmZlY3RlZF90YXJnZXRfbGV2ZWxgIG1lZGl1bWludCgxMSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYHNwZWxsVGFyZ2V0c2AgdGlueWludCgzKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgZG1nX211bHRpcGxpZXIxYCBmbG9hdCBOT1QgTlVMTCwKICBgZG1nX211bHRpcGxpZXIyYCBmbG9hdCBOT1QgTlVMTCwKICBgZG1nX211bHRpcGxpZXIzYCBmbG9hdCBOT1QgTlVMTCwKICBQUklNQVJZIEtFWSAgKGBzcGVsbElEYCkKKSBFTkdJTkU9TXlJU0FNIERFRkFVTFQgQ0hBUlNFVD11dGY4IFJPV19GT1JNQVQ9RklYRUQgQ09NTUVOVD0nU3BlbGxzJzs=",
			"SpellDuration.dbc" => "PGJyIC8+PGJyIC8+LS0gU3BlbGxEdXJhdGlvbi5kYmMKRFJPUCBUQUJMRSBJRiBFWElTVFMgYGZyZWVkb21oZWFkX3NwZWxsZHVyYXRpb25gOwpDUkVBVEUgVEFCTEUgYGZyZWVkb21oZWFkX3NwZWxsZHVyYXRpb25gICgKICBgZHVyYXRpb25JRGAgc21hbGxpbnQoMykgdW5zaWduZWQgTk9UIE5VTEwsCiAgYGR1cmF0aW9uQmFzZWAgaW50KDEwKSBzaWduZWQgTk9UIE5VTEwsCiAgUFJJTUFSWSBLRVkgIChgZHVyYXRpb25JRGApCikgRU5HSU5FPU15SVNBTSBERUZBVUxUIENIQVJTRVQ9dXRmOCBST1dfRk9STUFUPUZJWEVEOw==",
			"SpellRange.dbc" => "PGJyIC8+PGJyIC8+LS0gU3BlbGxSYW5nZS5kYmMKRFJPUCBUQUJMRSBJRiBFWElTVFMgYGZyZWVkb21oZWFkX3NwZWxscmFuZ2VgOwpDUkVBVEUgVEFCTEUgYGZyZWVkb21oZWFkX3NwZWxscmFuZ2VgICgKICBgcmFuZ2VJRGAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgcmFuZ2VNaW5gIGZsb2F0IE5PVCBOVUxMLAogIGByYW5nZU1pbkZyaWVuZGx5YCBmbG9hdCBOT1QgTlVMTCwKICBgcmFuZ2VNYXhgIGZsb2F0IE5PVCBOVUxMLAogIGByYW5nZU1heEZyaWVuZGx5YCBmbG9hdCBOT1QgTlVMTCwKICBgbmFtZV9sb2MwYCB2YXJjaGFyKDI1NSkgTk9UIE5VTEwsCiAgUFJJTUFSWSBLRVkgIChgcmFuZ2VJRGApCikgRU5HSU5FPU15SVNBTSBERUZBVUxUIENIQVJTRVQ9dXRmOCBST1dfRk9STUFUPUZJWEVEOw==",
			"SpellRadius.dbc" => "PGJyIC8+PGJyIC8+LS0gU3BlbGxSYWRpdXMuZGJjCkRST1AgVEFCTEUgSUYgRVhJU1RTIGBmcmVlZG9taGVhZF9zcGVsbHJhZGl1c2A7CkNSRUFURSBUQUJMRSBgZnJlZWRvbWhlYWRfc3BlbGxyYWRpdXNgICgKICBgcmFkaXVzSURgIHNtYWxsaW50KDUpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGByYWRpdXNCYXNlYCBmbG9hdCBOT1QgTlVMTCwKICBQUklNQVJZIEtFWSAgKGByYWRpdXNJRGApCikgRU5HSU5FPU15SVNBTSBERUZBVUxUIENIQVJTRVQ9dXRmOCBST1dfRk9STUFUPUZJWEVEOw==",
			"SpellItemEnchantment.dbc" => "PGJyIC8+PGJyIC8+LS0gU3BlbGxJdGVtRW5jaGFudG1lbnQuZGJjCkRST1AgVEFCTEUgSUYgRVhJU1RTIGBmcmVlZG9taGVhZF9pdGVtZW5jaGFudG1ldGA7CkNSRUFURSBUQUJMRSBgZnJlZWRvbWhlYWRfaXRlbWVuY2hhbnRtZXRgICgKICBgaXRlbWVuY2hhbnRtZXRJRGAgc21hbGxpbnQoMykgdW5zaWduZWQgTk9UIE5VTEwsCiAgYHRleHRfbG9jMGAgdGV4dCBOT1QgTlVMTCwKICBQUklNQVJZIEtFWSAgKGBpdGVtZW5jaGFudG1ldElEYCkKKSBFTkdJTkU9TXlJU0FNIERFRkFVTFQgQ0hBUlNFVD11dGY4IFJPV19GT1JNQVQ9RklYRUQ7",
			"GemProperties.dbc" => "PGJyIC8+PGJyIC8+LS0gR2VtUHJvcGVydGllcy5kYmMKRFJPUCBUQUJMRSBJRiBFWElTVFMgYGZyZWVkb21oZWFkX2dlbXByb3BlcnRpZXNgOwpDUkVBVEUgVEFCTEUgYGZyZWVkb21oZWFkX2dlbXByb3BlcnRpZXNgICgKICBgZ2VtcHJvcGVydGllc0lEYCBzbWFsbGludCgzKSB1bnNpZ25lZCBOT1QgTlVMTCwKICBgaXRlbWVuY2hhbnRtZXRJRGAgc21hbGxpbnQoMykgdW5zaWduZWQgTk9UIE5VTEwsCiAgUFJJTUFSWSBLRVkgIChgZ2VtcHJvcGVydGllc0lEYCkKKSBFTkdJTkU9TXlJU0FNIERFRkFVTFQgQ0hBUlNFVD11dGY4IFJPV19GT1JNQVQ9RklYRUQ7",
			"Talent.dbc" => "PGJyIC8+PGJyIC8+Ci0tIFRhbGVudC5kYmMKRFJPUCBUQUJMRSBJRiBFWElTVFMgYGZyZWVkb21oZWFkX3RhbGVudGA7CkNSRUFURSBUQUJMRSBgZnJlZWRvbWhlYWRfdGFsZW50YCAoCiAgYGlkYCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIGRlZmF1bHQgJzAnLAogIGB0YWJgIG1lZGl1bWludCgxMSkgdW5zaWduZWQgZGVmYXVsdCAnMCcsCiAgYHJvd2AgdGlueWludCgyKSB1bnNpZ25lZCBkZWZhdWx0ICcwJywKICBgY29sYCB0aW55aW50KDIpIHVuc2lnbmVkIGRlZmF1bHQgJzAnLAogIGByYW5rMWAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBkZWZhdWx0ICcwJywKICBgcmFuazJgIG1lZGl1bWludCgxMSkgdW5zaWduZWQgZGVmYXVsdCAnMCcsCiAgYHJhbmszYCBtZWRpdW1pbnQoMTEpIHVuc2lnbmVkIGRlZmF1bHQgJzAnLAogIGByYW5rNGAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBkZWZhdWx0ICcwJywKICBgcmFuazVgIG1lZGl1bWludCgxMSkgdW5zaWduZWQgZGVmYXVsdCAnMCcsCiAgYGRlcGVuZHNPbmAgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBkZWZhdWx0ICcwJywKICBgZGVwZW5kc09uUmFua2AgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBkZWZhdWx0ICcwJywKICBgcGV0bWFza2AgaW50KDExKSB1bnNpZ25lZCBkZWZhdWx0ICcwJywKICBQUklNQVJZIEtFWShgaWRgKSwKICBVTklRVUUgS0VZIGBwb3NgIChgdGFiYCxgcm93YCxgY29sYCxgcGV0bWFza2ApCikgRU5HSU5FPU15SVNBTSBERUZBVUxUIENIQVJTRVQ9dXRmOCBST1dfRk9STUFUPUZJWEVEOw==",
			"TalentTab.dbc" => "PGJyIC8+PGJyIC8+LS0gVGFsZW50VGFiLmRiYwpEUk9QIFRBQkxFIElGIEVYSVNUUyBgZnJlZWRvbWhlYWRfdGFsZW50dGFiYDsKQ1JFQVRFIFRBQkxFIGBmcmVlZG9taGVhZF90YWxlbnR0YWJgICgKICBgaWRgIG1lZGl1bWludCgxMSkgdW5zaWduZWQgZGVmYXVsdCAnMCcsCiAgYG5hbWVfbG9jMGAgdmFyY2hhcigzMikgTk9UIE5VTEwgZGVmYXVsdCAnJywKICBgY2xhc3Nlc2AgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBkZWZhdWx0ICcwJywKICBgcGV0c2AgbWVkaXVtaW50KDExKSB1bnNpZ25lZCBkZWZhdWx0ICcwJywKICBgb3JkZXJgIHRpbnlpbnQoMSkgdW5zaWduZWQgZGVmYXVsdCAnMCcsCiAgUFJJTUFSWSBLRVkgKGBpZGApLAogIFVOSVFVRSBLRVkgYHBvc2AgKGBjbGFzc2VzYCxgcGV0c2AsYG9yZGVyYCkKKSBFTkdJTkU9TXlJU0FNIERFRkFVTFQgQ0hBUlNFVD11dGY4IFJPV19GT1JNQVQ9RklYRUQ7",
			"FactionTemplate.dbc" => "PGJyIC8+PGJyIC8+LS0gRmFjdGlvblRlbXBsYXRlLmRiYwpEUk9QIFRBQkxFIElGIEVYSVNUUyBgZnJlZWRvbWhlYWRfZmFjdGlvbnRlbXBsYXRlYDsKQ1JFQVRFIFRBQkxFIGBmcmVlZG9taGVhZF9mYWN0aW9udGVtcGxhdGVgICgKICBgZmFjdGlvbnRlbXBsYXRlSURgIHNtYWxsaW50KDQpIHVuc2lnbmVkIE5PVCBOVUxMLAogIGBmYWN0aW9uSURgIHNtYWxsaW50KDQpIE5PVCBOVUxMLAogIGBBYCBzbWFsbGludCgxKSBOT1QgTlVMTCBDT01NRU5UICdBbGlhbmNlOiAtMSAtIGhvc3RpbGUsIDEgLSBmcmllbmRseSwgMCAtIG5ldXRyYWwnLAogIGBIYCBzbWFsbGludCgxKSBOT1QgTlVMTCBDT01NRU5UICdIb3JkZTogLTEgLSBob3N0aWxlLCAxIC0gZnJpZW5kbHksIDAgLSBuZXV0cmFsJywKICBQUklNQVJZIEtFWSAgKGBmYWN0aW9udGVtcGxhdGVJRGApCikgRU5HSU5FPU15SVNBTSBERUZBVUxUIENIQVJTRVQ9dXRmOCBST1dfRk9STUFUPUZJWEVEOw==",
			"Faction.dbc" => "PGJyIC8+PGJyIC8+LS0gRmFjdGlvbi5kYmMKRFJPUCBUQUJMRSBJRiBFWElTVFMgYGZyZWVkb21oZWFkX2ZhY3Rpb25zYDsKQ1JFQVRFIFRBQkxFIGBmcmVlZG9taGVhZF9mYWN0aW9uc2AgKAogIGBmYWN0aW9uSURgIG1lZGl1bWludCgxMSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYHJlcHV0YXRpb25MaXN0SURgIG1lZGl1bWludCgxMSkgTk9UIE5VTEwsCiAgYHRlYW1gIG1lZGl1bWludCgxMSkgdW5zaWduZWQgTk9UIE5VTEwsCiAgYHNpZGVgIHRpbnlpbnQoMSkgTk9UIE5VTEwsCiAgYG5hbWVfbG9jMGAgdmFyY2hhcigyNTUpIE5PVCBOVUxMLAogIGBkZXNjcmlwdGlvbjFfbG9jMGAgdGV4dCBDT01NRU5UICdEZXNjcmlwdGlvbiBmcm9tIGNsaWVudCcsCiAgYGRlc2NyaXB0aW9uMl9sb2MwYCB0ZXh0IENPTU1FTlQgJ0Rlc2NyaXB0aW9uIGZyb20gd293d2lraS5jb20nLAogIFBSSU1BUlkgS0VZICAoYGZhY3Rpb25JRGApCikgRU5HSU5FPU15SVNBTSBERUZBVUxUIENIQVJTRVQ9dXRmOCBST1dfRk9STUFUPUZJWEVEOw==",
			"Group.dbc" => "PGJyIC8+PGJyIC8+LS0gV29ybGRNYXBBcmVhLmRiYywgTWFwLmRiYywgQXJlYVRhYmxlLmRiYwpEUk9QIFRBQkxFIElGIEVYSVNUUyBgZnJlZWRvbWhlYWRfem9uZXNgOwpDUkVBVEUgVEFCTEUgYGZyZWVkb21oZWFkX3pvbmVzYCAoCiAgYG1hcElEYCBzbWFsbGludCgzKSB1bnNpZ25lZCBOT1QgTlVMTCBDT01NRU5UICdNYXAgSWRlbnRpZmllcicsCiAgYGFyZWF0YWJsZUlEYCAgc21hbGxpbnQoMykgdW5zaWduZWQgTk9UIE5VTEwgQ09NTUVOVCAnWm9uZSBJZCcsCiAgYG5hbWVfbG9jMGAgdmFyY2hhcigyNTUpIE5PVCBOVUxMIENPTU1FTlQgJ01hcCBOYW1lJywKICBgeF9taW5gIGZsb2F0IE5PVCBOVUxMIERFRkFVTFQgMC4wLAogIGB5X21pbmAgZmxvYXQgTk9UIE5VTEwgREVGQVVMVCAwLjAsCiAgYHhfbWF4YCBmbG9hdCBOT1QgTlVMTCBERUZBVUxUIDAuMCwKICBgeV9tYXhgIGZsb2F0IE5PVCBOVUxMIERFRkFVTFQgMC4wLAogIGB0eXBlYCB0aW55aW50KDIpIHVuc2lnbmVkIE5PVCBOVUxMCikgRU5HSU5FPU15SVNBTSBERUZBVUxUIENIQVJTRVQ9dXRmOCBST1dfRk9STUFUPUZJWEVEIENPTU1FTlQ9J01hcHMnOw==",
		);
		return $Headers[$DBCName];
	}
}

?>